In [1]:
import numpy as np
from scipy.sparse import csr_matrix
import pdb
from time import time
import cPickle as pickle
import os
# --------
import theano
from theano import tensor as T
import lasagne
from lasagne.layers import *
from lasagne.objectives import *
from lasagne.nonlinearities import *
from lasagne.updates import *
from lasagne.utils import *
from lasagne.regularization import *

import itertools

In [4]:
import sys
sys.path.append("..")
import create_data

In [93]:
bottleneck = 25
net1_cfg = create_data.get_net(
    (create_data.ui_encoder),
    {"bottleneck":bottleneck, "code":bottleneck, "learning_rate":0.1, "nonlinearity":sigmoid, "optimiser":"nesterov_momentum", "mode":"both"})

compiling theano functions...
<lasagne.layers.input.InputLayer object at 0x126692d90> (None, 65133)
<lasagne.layers.dense.DenseLayer object at 0x1261afb50> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261bcd10> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261d9f90> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261e8e10> (None, 65133)
number of params: 3323108
<lasagne.layers.input.InputLayer object at 0x113120e90> (None, 71567)
<lasagne.layers.dense.DenseLayer object at 0x1131287d0> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x113128f10> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x113128c90> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261f89d0> (None, 71567)
number of params: 3651242
params = [W, b, W, b, W, b, W, b, W, b, W, b, W, b, W, b]


In [94]:
for layer in get_all_layers(net1_cfg["l_out_i"]):
    print layer, layer.output_shape

<lasagne.layers.input.InputLayer object at 0x126692d90> (None, 65133)
<lasagne.layers.dense.DenseLayer object at 0x1261afb50> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261bcd10> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261d9f90> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261e8e10> (None, 65133)


In [95]:
for layer in get_all_layers(net1_cfg["l_out_u"]):
    print layer, layer.output_shape

<lasagne.layers.input.InputLayer object at 0x113120e90> (None, 71567)
<lasagne.layers.dense.DenseLayer object at 0x1131287d0> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x113128f10> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x113128c90> (None, 25)
<lasagne.layers.dense.DenseLayer object at 0x1261f89d0> (None, 71567)


In [26]:
net1_cfg


{'code_fn_i': <theano.compile.function_module.Function at 0x118cce910>,
 'code_fn_u': <theano.compile.function_module.Function at 0x118ce2c10>,
 'l_out_i': <lasagne.layers.dense.DenseLayer at 0x113110550>,
 'l_out_u': <lasagne.layers.dense.DenseLayer at 0x113110f10>,
 'loss_fn': <theano.compile.function_module.Function at 0x118a56e90>,
 'lr': <TensorType(float64, scalar)>,
 'train_fn': <theano.compile.function_module.Function at 0x1185f4ed0>}

In [96]:
with open("25-25.model") as f:
    dat = pickle.load(f)
    params_i = dat[0]
    params_u = dat[1]
    set_all_param_values(net1_cfg["l_out_i"], params_i)
    set_all_param_values(net1_cfg["l_out_u"], params_u)

In [104]:
params_i[2][0:10,0:10]

array([[-0.01227422,  0.33293974,  0.19250999, -0.1163257 , -0.1270375 ,
         0.11828431, -0.14832671, -0.12354697,  0.21742257,  0.18528645],
       [-0.32743409, -0.12415475, -0.09927682,  0.09288511, -0.21406843,
        -0.10749659, -0.2894944 , -0.33860025,  0.27805173,  0.33495697],
       [ 0.32029226,  0.50546241, -0.00061859,  0.39547402,  0.34319267,
         0.09334932,  0.56411779, -0.07826139,  0.16967066,  0.31222349],
       [ 0.21068595,  0.31042519, -0.02513475,  0.08753958, -0.31082827,
         0.01108275, -0.01850634, -0.13991237,  0.03181922, -0.19827157],
       [-0.15630689, -0.02627443,  0.0697992 ,  0.26905671, -0.15178277,
         0.44489771,  0.33548516,  0.44377539,  0.07470329, -0.13700899],
       [ 0.47787485,  0.27530327, -0.06247965,  0.12468963,  0.41312572,
         0.31174806,  0.34956387, -0.12727726,  0.43104559,  0.43693721],
       [ 0.11644754, -0.00360599,  0.13655266, -0.22930831, -0.26166332,
         0.03177318,  0.23263986, -0.00325965

In [105]:
params_u[2][0:10,0:10]

array([[  6.41373023e-02,  -1.95357800e-01,   5.58090806e-02,
         -2.01664463e-01,  -2.88541526e-01,  -1.61801144e-01,
         -1.84139743e-01,   1.75837070e-01,  -3.13664645e-01,
         -1.20617613e-01],
       [ -1.98102057e-01,   3.07705015e-01,   2.99916327e-01,
         -3.01868111e-01,  -3.26394320e-01,  -2.49170542e-01,
         -1.97842926e-01,   3.07546500e-02,   2.64034420e-01,
          3.11691880e-01],
       [ -2.85413682e-01,  -2.63856918e-01,   3.04853171e-01,
         -3.09802979e-01,   2.66072959e-01,   1.37466975e-02,
         -2.61766165e-01,   1.13286510e-01,  -2.61671767e-02,
         -1.27040654e-01],
       [ -1.82190418e-01,   1.69807926e-01,  -1.41572759e-01,
         -2.19979882e-01,   2.76727200e-01,   2.81139821e-01,
          8.49171914e-03,   1.07202949e-02,   1.41776666e-01,
          1.63832426e-01],
       [  1.22123964e-01,  -3.33161771e-01,   3.19043219e-01,
          1.45682603e-01,  -1.35043515e-02,  -1.46022914e-02,
         -1.71828166e-01

In [97]:
net1_cfg["l_out_u"].input_layer.input_layer.W.get_value()[0:5,0:5]

array([[ 0.0641373 , -0.1953578 ,  0.05580908, -0.20166446, -0.28854153],
       [-0.19810206,  0.30770501,  0.29991633, -0.30186811, -0.32639432],
       [-0.28541368, -0.26385692,  0.30485317, -0.30980298,  0.26607296],
       [-0.18219042,  0.16980793, -0.14157276, -0.21997988,  0.2767272 ],
       [ 0.12212396, -0.33316177,  0.31904322,  0.1456826 , -0.01350435]])

In [98]:
net1_cfg["l_out_i"].input_layer.input_layer.W.get_value()[0:5,0:5]

array([[ 0.0641373 , -0.1953578 ,  0.05580908, -0.20166446, -0.28854153],
       [-0.19810206,  0.30770501,  0.29991633, -0.30186811, -0.32639432],
       [-0.28541368, -0.26385692,  0.30485317, -0.30980298,  0.26607296],
       [-0.18219042,  0.16980793, -0.14157276, -0.21997988,  0.2767272 ],
       [ 0.12212396, -0.33316177,  0.31904322,  0.1456826 , -0.01350435]])

In [106]:
net1_cfg["l_out_i"].input_layer.input_layer.W == net1_cfg["l_out_u"].input_layer.input_layer.W

True

In [116]:
params1 = get_all_params(net1_cfg["l_out_i"], trainable=True)

In [117]:
params2 = get_all_params(net1_cfg["l_out_u"], trainable=True)

In [119]:
param_set = set()
for elem in params1:
    param_set.add(elem)
for elem in params2:
    param_set.add(elem)

In [122]:
list(param_set)

[b, b, W, b, b, b, W, W, b, W, W, b, W, W]